services:
  - type: web
    name: websocket-proxy
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --worker-connections 1000 --bind 0.0.0.0:$PORT --timeout 120 --config gunicorn_config.py app:app
    plan: free  # или starter для платного
    envVars:
      - key: HTTP_PROXY
        sync: false
      - key: HTTPS_PROXY
        sync: false
      - key: PROXY_URL
        sync: false
      - key: PORT
        value: 5000
      - key: WS_PORT
        value: 8765

